In [1]:
# no. of elements
m = 4

4

In [28]:
# generate non symmetrical matrix (convert randn*10 to integer vector)
rd(x) = round(Int, x)

rd (generic function with 1 method)

In [38]:
# reshape vector to 4x4 matrix
N = reshape(rd.(10 * randn(16)), m, m)

4×4 Matrix{Int64}:
  9   -4  -13    7
  1   -3   15    3
  0    7   -2  -12
 -8  -16   -2   -2

In [39]:
# generate symmetrical matrix
S = rd.(N' * N/m^2)

4×4 Matrix{Int64}:
  9   6  -5   5
  6  21   2  -6
 -5   2  25  -1
  5  -6  -1  13

In [40]:
# generate column vector (4x1)
w = [-1 0 1 2]'

4×1 adjoint(::Matrix{Int64}) with eltype Int64:
 -1
  0
  1
  2

### For multiplication of vector with symmetrical matrix

In [42]:
S * w

4×1 Matrix{Int64}:
  -4
 -16
  28
  20

In [43]:
(S * w)' # same but transposed

1×4 adjoint(::Matrix{Int64}) with eltype Int64:
 -4  -16  28  20

In [44]:
w * S # mismatch, as described in error message below

LoadError: DimensionMismatch("matrix A has dimensions (4,1), matrix B has dimensions (4,4)")

In [45]:
w' * S' # same as (S*w)' (LIVE EVIL mnemonic)

1×4 Matrix{Int64}:
 -4  -16  28  20

In [46]:
w' * S # as above, as S == S'

1×4 Matrix{Int64}:
 -4  -16  28  20

### Multiplication of vector and Non-symmetrical Matrix

In [47]:
N * w

4×1 Matrix{Int64}:
  -8
  20
 -26
   2

In [48]:
(N * w)' # just transposed

1×4 adjoint(::Matrix{Int64}) with eltype Int64:
 -8  20  -26  2

In [49]:
w * N # Dimension mismatch, just like with w * S

LoadError: DimensionMismatch("matrix A has dimensions (4,1), matrix B has dimensions (4,4)")

In [51]:
w' * N' # same as (N * w)' (LIVE-EVIL mnemonic)

1×4 Matrix{Int64}:
 -8  20  -26  2

In [52]:
w' * N # not the same, as N != N'

1×4 Matrix{Int64}:
 -25  -21  7  -23