In [2]:
n = 4

4

In [14]:
# generate a 4x4 matrix of random integers
r(x) = round(Int, x)
a = r.(10*randn(n,n))

4×4 Matrix{Int64}:
  -3   4  -8  11
 -10  19  -6   4
 -13  -6  -8  18
  -1  -6   8  -6

In [11]:
# generate identity matrix
eye(x) = [row == col for row in 1:x, col in 1:x]

eye (generic function with 1 method)

In [12]:
i = eye(n)

4×4 Matrix{Bool}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1

In [13]:
# generate zeros matrix
z = zeros(4,4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [15]:
# test both identities
# A * I = A
isequal(a*i, a)

true

In [16]:
# A = A * I
isequal(a, a*i)

true

In [17]:
# A not equal to A+I
isequal(a, a+i)

false

In [18]:
# A = A + 0
isequal(a+z, a)

true

In [19]:
# A - 0 = A
isequal(a-z, a)

true

In [20]:
# 0 - A = -A
isequal(z-a, -a)

true

In [21]:
# A * 0 = 0
iszero(a * z)

true

In [24]:
# A*I = A-0
isequal(a*i, a-z)

true